# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0acd911bc93977ffe6875d9a9aec78c7782b8e64393209cef8eef450e5e043f235a79e4f3c4b1ac5b800ffe6de598112f598ad57c7f3b8eb5ab0e54206bcfd52

test:
  secret_key_base: 6d60e6073ff6e8a4d3108f97925f02b03a8669b799627680bb9aee32e72556843509f5a96b0d9f16e405aba8801ac993cfa5173a4cadf2c4aec53ba552edf687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
